# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, feature/config-github-actions]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: write

env:
  tag_name: v1.0.2 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build-linux:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v3
  #       with:
  #         python-version: "3.10"
  #         cache: "pip"
  #     - name: Install deps
  #       run: |
  #         pip install -r requirements.txt
  #     - name: Copy sdk
  #       run: |
  #         mkdir -p venv/lib/python3.10/site-packages/zcrmsdk
  #         cp -r $LD_LIBRARY_PATH/python3.10/site-packages/zcrmsdk venv/lib/python3.10/site-packages/zcrmsdk
  #     - name: Build
  #       run: pyinstaller main-ci.spec
  #     - name: Zip dist folder
  #       run: |
  #         tar -cvzf xml-sepe.zip dist
  #         ls -la
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: xml-sepe.zip
      #     tag_name: v1.0.0
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: py
        with:
          python-version: "3.10"
          cache: "pip"
      - run: |
          pip install -r requirements.txt
      - name: Copy sdk
        run: |
          mkdir -p venv/lib/python3.10/site-packages/zcrmsdk
          pip list -v
          echo '${{ steps.py.outputs.python-path }}'
          cp -r c:/usr/local/lib/python3.10/site-packages/zcrmsdk venv/lib/python3.10/site-packages/zcrmsdk
      - name: Build
        run: pyinstaller main-ci.spec
      - name: Zip dist folder
        uses: TheDoctor0/zip-release@0.6.2
        with:
          path: 'dist'
          filename: 'xml-sepe-windows.zip'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: xml-sepe-windows.zip
          tag_name: $tag_name
